name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: stefda/action-cloud-run@v1.0
      - name: Deploy service to Cloud Run
        with:
          image: gcr.io/leadmrktr/pasteit
          service: pasteit
          project: leadmrktr
          region:  asia-northeast1
          service key: ${{ secrets.GCLOUD_AUTH }}
