name: Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build .  --file DockerfileCloudRun --build-arg GOOGLE_KEY=${{ secrets.GCLOUD_AUTH }}
