- name: Deploy service to Cloud Run
  uses: stefda/action-cloud-run@v1.0
  with:
    image: gcr.io/leadmrktr/pasteit
    service: pasteit
    project: leadmrktr
    region:  asia-northeast1
    service key: ${{ secrets.GCLOUD_AUTH }}
